clone:
  depth: full
pipelines:
  default:
    - step:
        name: Sync to GitHub
        script:
          - git clone --mirror $BITBUCKET_CLONE_DIR temp_dir
          - cd temp_dir
          - git push https://$GITHUB_TOKEN@github.com/Siqsuruq/oodz.git